import type { CompanionDefinition } from '../engine/companions/types';

/**
 * The authored roster: 10 common, 8 rare, 6 epic, 4 legendary, 2 mythical.
 *
 * Only identity lives here - name, flavour, class, cadence, ability and
 * silhouette. Every power number is derived from class x rarity x star in
 * `companionTuning.ts`, so rebalancing the game never means editing thirty
 * entries, and a new companion is one object rather than one object plus a
 * stat block somebody has to keep in line with its neighbours.
 *
 * `range` is measured from the companion's own formation slot, not from the
 * mage - front-row reaches are short because the row already stands forward.
 */
export const COMPANIONS: readonly CompanionDefinition[] = [
  /* ------------------------------------------------------------ common --- */
  {
    id: 'hedge_warden',
    name: 'Hedge Warden',
    description: 'A village watchman with a door for a shield. He has never won a fight, but he has ended a great many.',
    rarity: 'common',
    companionClass: 'vanguard',
    kind: 'humanoid',
    modelKey: 'humanoid_heavy',
    attackInterval: 2.6,
    range: 2,
    ability: { id: 'guard', magnitude: 0.06, cooldown: 0 },
    tags: ['greenfields'],
  },
  {
    id: 'cairn_tortoise',
    name: 'Cairn Tortoise',
    description: 'Moss and old milestones have grown into its shell. It arrives when it arrives.',
    rarity: 'common',
    companionClass: 'vanguard',
    kind: 'creature',
    modelKey: 'beast_quadruped',
    attackInterval: 3.2,
    range: 2,
    ability: { id: 'guard', magnitude: 0.07, cooldown: 0 },
    tags: ['beast', 'greenfields'],
  },
  {
    id: 'bramble_pup',
    name: 'Bramble Pup',
    description: 'Half hound, half thornbush, wholly delighted to be here.',
    rarity: 'common',
    companionClass: 'bruiser',
    kind: 'creature',
    modelKey: 'beast_quadruped',
    attackInterval: 1.9,
    range: 2.1,
    ability: { id: 'strike', magnitude: 0.5, cooldown: 6 },
    tags: ['beast', 'plant'],
  },
  {
    id: 'roadside_brawler',
    name: 'Roadside Brawler',
    description: 'Fights for lodging, loses at dice, and has opinions about every bridge on the Ashen Road.',
    rarity: 'common',
    companionClass: 'bruiser',
    kind: 'humanoid',
    modelKey: 'humanoid_light',
    attackInterval: 2,
    range: 2.1,
    ability: { id: 'strike', magnitude: 0.55, cooldown: 6 },
    tags: ['ashen-road'],
  },
  {
    id: 'cutpurse_sprite',
    name: 'Cutpurse Sprite',
    description: 'Takes one small thing from everything it touches. Nobody has worked out where any of it goes.',
    rarity: 'common',
    companionClass: 'trickster',
    kind: 'creature',
    modelKey: 'floating_orb',
    attackInterval: 1.1,
    range: 3.4,
    ability: { id: 'strike', magnitude: 0.35, cooldown: 5 },
    tags: ['fae'],
  },
  {
    id: 'sling_boy',
    name: 'Sling Boy',
    description: 'Twelve years old, frighteningly accurate, and absolutely not going home.',
    rarity: 'common',
    companionClass: 'ranger',
    kind: 'humanoid',
    modelKey: 'humanoid_light',
    attackInterval: 1.6,
    range: 8.5,
    ability: { id: 'strike', magnitude: 0.45, cooldown: 6 },
    tags: ['greenfields'],
  },
  {
    id: 'quiver_finch',
    name: 'Quiver Finch',
    description: 'It sheds its pin-feathers at speed and grows them back by morning.',
    rarity: 'common',
    companionClass: 'ranger',
    kind: 'creature',
    modelKey: 'winged_creature',
    attackInterval: 1.5,
    range: 8.5,
    ability: { id: 'volley', magnitude: 0.22, cooldown: 7 },
    tags: ['beast', 'flying'],
  },
  {
    id: 'hearth_candle',
    name: 'Hearth Candle',
    description: 'A small warm light that refuses to go out while anyone is still standing.',
    rarity: 'common',
    companionClass: 'support',
    kind: 'creature',
    modelKey: 'floating_orb',
    attackInterval: 3,
    range: 9,
    ability: { id: 'mend', magnitude: 0.05, cooldown: 6 },
    tags: ['spirit'],
  },
  {
    id: 'wandering_herbalist',
    name: 'Wandering Herbalist',
    description: 'Knows which of the Whispering Woods you may eat. Mostly.',
    rarity: 'common',
    companionClass: 'support',
    kind: 'humanoid',
    modelKey: 'humanoid_robed',
    attackInterval: 3,
    range: 9,
    ability: { id: 'mend', magnitude: 0.06, cooldown: 6 },
    tags: ['whispering-woods'],
  },
  {
    id: 'chalk_apprentice',
    name: 'Chalk Apprentice',
    description: 'Draws the circle correctly about four times in five, which is a good deal better than it sounds.',
    rarity: 'common',
    companionClass: 'arcanist',
    kind: 'humanoid',
    modelKey: 'humanoid_robed',
    attackInterval: 2.4,
    range: 9,
    ability: { id: 'strike', magnitude: 0.6, cooldown: 7 },
    tags: ['arcane'],
  },

  /* -------------------------------------------------------------- rare --- */
  {
    id: 'ashroad_sellsword',
    name: 'Ashroad Sellsword',
    description: 'Paid in advance, every time, without exception. She has buried too many employers to extend credit.',
    rarity: 'rare',
    companionClass: 'bruiser',
    kind: 'humanoid',
    modelKey: 'humanoid_heavy',
    attackInterval: 1.8,
    range: 2.1,
    ability: { id: 'strike', magnitude: 0.8, cooldown: 5.5 },
    tags: ['ashen-road'],
  },
  {
    id: 'mossback_bulwark',
    name: 'Mossback Bulwark',
    description: 'Something ancient sleeping under a hill, roused by the noise and mildly annoyed about it.',
    rarity: 'rare',
    companionClass: 'vanguard',
    kind: 'creature',
    modelKey: 'beast_quadruped',
    attackInterval: 3,
    range: 2,
    ability: { id: 'guard', magnitude: 0.1, cooldown: 0 },
    tags: ['beast', 'whispering-woods'],
  },
  {
    id: 'fenmarch_pikeman',
    name: 'Fenmarch Pikeman',
    description: 'Holds a line of one as though it were a line of forty. It usually works.',
    rarity: 'rare',
    companionClass: 'vanguard',
    kind: 'humanoid',
    modelKey: 'humanoid_heavy',
    attackInterval: 2.4,
    range: 2,
    ability: { id: 'guard', magnitude: 0.09, cooldown: 0 },
    tags: ['soldier'],
  },
  {
    id: 'thicket_stalker',
    name: 'Thicket Stalker',
    description: 'You will not see it until it wants seeing, and by then it has already bitten something important.',
    rarity: 'rare',
    companionClass: 'trickster',
    kind: 'creature',
    modelKey: 'beast_quadruped',
    attackInterval: 1.2,
    range: 3.4,
    ability: { id: 'hex', magnitude: 0.12, cooldown: 7 },
    tags: ['beast', 'whispering-woods'],
  },
  {
    id: 'verge_longbow',
    name: 'Verge Longbow',
    description: 'Counts the paces to every landmark on the road out of habit, and never misses at a number she has counted.',
    rarity: 'rare',
    companionClass: 'ranger',
    kind: 'humanoid',
    modelKey: 'humanoid_light',
    attackInterval: 1.5,
    range: 8.5,
    ability: { id: 'volley', magnitude: 0.35, cooldown: 6.5 },
    tags: ['greenfields'],
  },
  {
    id: 'emberfly_swarm',
    name: 'Emberfly Swarm',
    description: 'Individually harmless. There are never individually any of them.',
    rarity: 'rare',
    companionClass: 'arcanist',
    kind: 'creature',
    modelKey: 'floating_orb',
    attackInterval: 2.2,
    range: 9,
    ability: { id: 'wither', magnitude: 0.3, cooldown: 8 },
    tags: ['fire', 'swarm'],
  },
  {
    id: 'tallow_chirurgeon',
    name: 'Tallow Chirurgeon',
    description: 'Field medicine by candlelight. Do not ask what the candles are made of.',
    rarity: 'rare',
    companionClass: 'support',
    kind: 'humanoid',
    modelKey: 'humanoid_robed',
    attackInterval: 2.8,
    range: 9,
    ability: { id: 'mend', magnitude: 0.1, cooldown: 5.5 },
    tags: ['gravehollow'],
  },
  {
    id: 'copper_automaton',
    name: 'Copper Automaton',
    description: 'Wound each morning with a key that was lost some centuries ago. It has not stopped.',
    rarity: 'rare',
    companionClass: 'bruiser',
    kind: 'creature',
    modelKey: 'humanoid_heavy',
    attackInterval: 2,
    range: 2.1,
    ability: { id: 'strike', magnitude: 0.85, cooldown: 5.5 },
    tags: ['construct'],
  },

  /* -------------------------------------------------------------- epic --- */
  {
    id: 'whisperwood_dryad',
    name: 'Whisperwood Dryad',
    description: 'She remembers the wood before the road, and lends that patience to anyone standing near her.',
    rarity: 'epic',
    companionClass: 'support',
    kind: 'humanoid',
    modelKey: 'humanoid_robed',
    attackInterval: 2.6,
    range: 9,
    ability: { id: 'rally', magnitude: 0.18, cooldown: 9 },
    tags: ['plant', 'whispering-woods'],
  },
  {
    id: 'gravebell_acolyte',
    name: 'Gravebell Acolyte',
    description: 'Rings for the dead on the hour. Things that should not be listening always are.',
    rarity: 'epic',
    companionClass: 'arcanist',
    kind: 'humanoid',
    modelKey: 'humanoid_robed',
    attackInterval: 2.2,
    range: 9,
    ability: { id: 'wither', magnitude: 0.5, cooldown: 7 },
    tags: ['gravehollow', 'undead'],
  },
  {
    id: 'barrow_knight',
    name: 'Barrow Knight',
    description: 'Buried in his armour, and evidently unwilling to let that be the end of the matter.',
    rarity: 'epic',
    companionClass: 'vanguard',
    kind: 'humanoid',
    modelKey: 'humanoid_heavy',
    attackInterval: 2.5,
    range: 2,
    ability: { id: 'bulwark', magnitude: 0.35, cooldown: 10 },
    tags: ['gravehollow', 'undead'],
  },
  {
    id: 'silkstep_duelist',
    name: 'Silkstep Duelist',
    description: 'Three cuts before the first is noticed. She considers a fourth to be showing off.',
    rarity: 'epic',
    companionClass: 'trickster',
    kind: 'humanoid',
    modelKey: 'humanoid_light',
    attackInterval: 0.95,
    range: 3.4,
    ability: { id: 'strike', magnitude: 0.9, cooldown: 5 },
    tags: ['duelist'],
  },
  {
    id: 'hollowpine_elk',
    name: 'Hollowpine Elk',
    description: 'Its antlers are branches, and they are still growing.',
    rarity: 'epic',
    companionClass: 'bruiser',
    kind: 'creature',
    modelKey: 'beast_quadruped',
    attackInterval: 1.9,
    range: 2.1,
    ability: { id: 'strike', magnitude: 1.1, cooldown: 5.5 },
    tags: ['beast', 'plant'],
  },
  {
    id: 'stormquill_raptor',
    name: 'Stormquill Raptor',
    description: 'Rides the front of a storm and sheds a little of it wherever it stoops.',
    rarity: 'epic',
    companionClass: 'ranger',
    kind: 'creature',
    modelKey: 'winged_creature',
    attackInterval: 1.4,
    range: 8.5,
    ability: { id: 'volley', magnitude: 0.55, cooldown: 6 },
    tags: ['beast', 'flying', 'storm'],
  },

  /* --------------------------------------------------------- legendary --- */
  {
    id: 'sunless_knight',
    name: 'Sunless Knight',
    description: 'She swore to stand until the last light failed, and was not told the oath had been accepted.',
    rarity: 'legendary',
    companionClass: 'vanguard',
    kind: 'humanoid',
    modelKey: 'humanoid_heavy',
    attackInterval: 2.3,
    range: 2,
    ability: { id: 'bulwark', magnitude: 0.6, cooldown: 9 },
    tags: ['oathbound'],
  },
  {
    id: 'emberwing_drake',
    name: 'Emberwing Drake',
    description: 'Small for a drake. Enormous for everything standing in front of one.',
    rarity: 'legendary',
    companionClass: 'ranger',
    kind: 'creature',
    modelKey: 'winged_creature',
    attackInterval: 1.3,
    range: 8.5,
    ability: { id: 'volley', magnitude: 0.85, cooldown: 6 },
    tags: ['dragon', 'fire', 'flying'],
  },
  {
    id: 'mirrorcoat_thief',
    name: 'Mirrorcoat Thief',
    description: 'Steals the shape of a spell as it passes and gives it back slightly worse for the target.',
    rarity: 'legendary',
    companionClass: 'trickster',
    kind: 'humanoid',
    modelKey: 'humanoid_light',
    attackInterval: 1,
    range: 3.4,
    ability: { id: 'echo', magnitude: 0.25, cooldown: 4 },
    tags: ['arcane', 'thief'],
  },
  {
    id: 'ninefold_lamp',
    name: 'Vow of the Ninefold Lamp',
    description: 'Nine wicks, nine promises, and one of them is about you.',
    rarity: 'legendary',
    companionClass: 'support',
    kind: 'creature',
    modelKey: 'floating_orb',
    attackInterval: 2.5,
    range: 9,
    ability: { id: 'rally', magnitude: 0.3, cooldown: 8 },
    tags: ['spirit', 'oathbound'],
  },

  /* ---------------------------------------------------------- mythical --- */
  {
    id: 'choir_of_nine',
    name: 'Choir of Nine',
    description: 'Nine voices that were once nine casters, still finishing a spell they began a long time ago.',
    rarity: 'mythical',
    companionClass: 'arcanist',
    kind: 'creature',
    modelKey: 'floating_orb',
    attackInterval: 1.8,
    range: 9,
    ability: { id: 'echo', magnitude: 0.45, cooldown: 3 },
    tags: ['arcane', 'spirit'],
  },
  {
    id: 'pale_herald',
    name: 'The Pale Herald',
    description: 'Arrives only where someone is about to fall, and has been known to disagree with the outcome.',
    rarity: 'mythical',
    companionClass: 'support',
    kind: 'humanoid',
    modelKey: 'humanoid_robed',
    attackInterval: 2.4,
    range: 9,
    ability: { id: 'revive', magnitude: 0.5, cooldown: 12 },
    tags: ['gravehollow', 'spirit'],
  },
];
