import type { EnemyDefinition } from './types';

export const ENEMIES: readonly EnemyDefinition[] = [
  {
    id: 'moss_slime',
    name: 'Moss Slime',
    baseHealth: '4',
    healthGrowth: 1.16,
    baseAttack: '1',
    attackGrowth: 1.08,
    attackInterval: 2.4,
    rewardBase: '1',
    rewardGrowth: 1.12,
    modelKey: 'enemy/moss-slime',
    tags: ['beast'],
  },
  {
    id: 'briarling',
    name: 'Briarling',
    baseHealth: '5',
    healthGrowth: 1.16,
    baseAttack: '1.2',
    attackGrowth: 1.08,
    attackInterval: 2.1,
    rewardBase: '1.1',
    rewardGrowth: 1.12,
    modelKey: 'enemy/briarling',
    tags: ['plant'],
  },
  {
    id: 'road_imp',
    name: 'Road Imp',
    baseHealth: '4.5',
    healthGrowth: 1.17,
    baseAttack: '1.5',
    attackGrowth: 1.09,
    attackInterval: 1.8,
    rewardBase: '1.25',
    rewardGrowth: 1.12,
    modelKey: 'enemy/road-imp',
    tags: ['demon'],
  },
  {
    id: 'ash_beetle',
    name: 'Ash Beetle',
    baseHealth: '7',
    healthGrowth: 1.16,
    baseAttack: '1.1',
    attackGrowth: 1.08,
    attackInterval: 2.8,
    rewardBase: '1.4',
    rewardGrowth: 1.12,
    modelKey: 'enemy/ash-beetle',
    tags: ['armored'],
  },
  {
    id: 'hollow_crow',
    name: 'Hollow Crow',
    baseHealth: '3.8',
    healthGrowth: 1.16,
    baseAttack: '1.8',
    attackGrowth: 1.09,
    attackInterval: 1.55,
    rewardBase: '1.35',
    rewardGrowth: 1.12,
    modelKey: 'enemy/hollow-crow',
    tags: ['flying'],
  },
  {
    id: 'road_warden',
    name: 'Road Warden',
    baseHealth: '9',
    healthGrowth: 1.17,
    baseAttack: '2.2',
    attackGrowth: 1.09,
    attackInterval: 1.9,
    rewardBase: '4',
    rewardGrowth: 1.13,
    modelKey: 'boss/road-warden',
    tags: ['boss', 'guardian'],
  },
  {
    id: 'crypt_hound',
    name: 'Crypt Hound',
    baseHealth: '6',
    healthGrowth: 1.165,
    baseAttack: '1.6',
    attackGrowth: 1.09,
    attackInterval: 1.75,
    rewardBase: '1.6',
    rewardGrowth: 1.12,
    modelKey: 'enemy/crypt-hound',
    tags: ['undead'],
  },
  {
    id: 'ember_wisp',
    name: 'Ember Wisp',
    baseHealth: '4.4',
    healthGrowth: 1.165,
    baseAttack: '2',
    attackGrowth: 1.09,
    attackInterval: 1.45,
    rewardBase: '1.8',
    rewardGrowth: 1.12,
    modelKey: 'enemy/ember-wisp',
    tags: ['elemental'],
  },
] as const;
