import type { SpellMechanics } from '../engine/spell/SpellMechanics';
/** PLAYTEST defaults, not final balance. Fixed authored rules: 15% procs,
 * two Weakness stacks, five Momentum stacks, and half the next interval on a miss. */
export const SPELL_MECHANIC_DEFAULTS: Readonly<SpellMechanics> = {
  route: 'base',
  twinCast: false,
  piercingCast: false,
  chargedCast: false,
  // Holding two routes already costs twice the points, on a curve where each
  // point costs 27% more than the last. This keeps a blend a sideways move
  // rather than a strictly larger one; 1 removes the penalty entirely.
  routeBlendScale: 0.75,
  explosive: false,
  meteor: false,
  dot: false,
  contagion: false,
  weakness: false,
  ruin: false,
  chain: false,
  driving: false,
  kinetic: false,
  momentum: false,
  overdrive: false,
  perfect: false,
  supercharge: false,
  execution: false,
  finalBlow: false,
  plaguefall: false,
  doomfall: false,
  blight: false,
  terminalVoltage: false,
  stormdrive: false,
  terminalVelocity: false,
  criticalOverload: false,
  deathSentence: false,
  obliteration: false,
  blastRadius: 1.65,
  explosionDamage: 0.35,
  meteorChance: 0.15,
  meteorDelay: 0.55,
  meteorDamage: 1.25,
  dotDamage: 0.18,
  dotDuration: 4,
  dotInterval: 1,
  contagionChance: 0.15,
  contagionRadius: 2.5,
  weaknessStrength: 0.12,
  weaknessDuration: 4,
  weaknessCap: 2,
  ruinChance: 0.15,
  ruinDuration: 3,
  ruinAmplification: 0.3,
  penetrations: 1,
  lineTolerance: 0.18,
  chainRadius: 3.2,
  piercedDamage: 1,
  forceGain: 0.3,
  forceCap: 2,
  momentumCap: 5,
  momentumSpeed: 0.06,
  momentumDuration: 3,
  overdriveSpeed: 1.8,
  overdriveDuration: 2.5,
  chargedDamage: 3,
  chargedInterval: 1.7,
  focusMax: 3,
  superchargeCap: 5,
  superchargeGain: 0.18,
  executeThreshold: 0.35,
  executeDamage: 0.3,
  finalBlowPower: 1.5,
  finalBlowExponent: 2,
  finalBlowLowBonus: 0.5,
  doomfallMultiplier: 3,
  blightStrength: 1.5,
  overloadCritGain: 0.2,
  woundedThreshold: 0.5,
  criticalThreshold: 0.2,
};
export const SPELL_SIDE_TUNING = {
  blastRadius: 0.35,
  explosionDamage: 0.15,
  dotDamage: 0.08,
  dotDuration: 1.5,
  weaknessStrength: 0.04,
  weaknessDuration: 1.5,
  penetrations: 1,
  piercedDamage: 0.15,
  forceGain: 0.15,
  forceCap: 1,
  momentumSpeed: 0.02,
  momentumDuration: 1,
  critChance: 0.05,
  critMultiplier: 0.3,
  chargedDamage: 0.4,
  chargedInterval: -0.15,
  executeDamage: 0.2,
  executeThreshold: 0.05,
  criticalMassChance: 0.1,
} as const;
